### PR TITLE
Add stylelint-processor-html. Add test. Update README.

### LINKED ISSUE #14: Add support to processors
I'd love to have support to processors listed on https://stylelint.io/user-guide/processors/

How can we implement that? Is it just a new entry on `package.json`?

### PR DESCRIPTION
**Pull request by KrisOlszewski**
* Add [stylelint-processor-html](https://github.com/ccbikai/stylelint-processor-html)
* Add test for `.html` and `.vue` files
* Update README

Fixes #14

### CODE REVIEW

**Comment by gilbarbara** [comment]
Thanks for the PR but we need tests too

**Comment by KrisOlszewski** [comment]
Sounds good. I'll add tests for processors.

**Comment by KrisOlszewski** [comment]
@gilbarbara I've reduced this PR to a single processor with accompanying test. I'll do my best to add other processors. Thanks!

**Comment by KrisOlszewski** [comment]
@gilbarbara have you had a chance to review this PR? Is there anything else I could do to get it merged with a new release? Thanks!

**Pull request merged**
